---
- name: Set the index.html path
  set_fact:
    file_path: /var/www/html

- name: Copy vars.html
  copy:
    src: vars.html
    dest: "{{ file_path }}/vars.html"
    owner: root
    group: root
    mode: 0755

- name: Add a link from index.html to vars.html
  lineinfile:
    path: "{{ file_path }}/index.html"
    line: <a href=vars.html>variable page</a>
    insertafter: EOF
  ignore_errors: "{{ ansible_check_mode }}"

- name: insert hostname from ansible facts
  lineinfile:
    path: "{{ file_path }}/vars.html"
    line: <p>my name is {{ ansible_hostname }}.</p>
  ignore_errors: "{{ ansible_check_mode }}"

- name: Add link from vars.html back to index.html
  lineinfile:
    path: "{{ file_path }}/vars.html"
    line: <a href=index.html>back to index.html</a>
    insertafter: EOF
  ignore_errors: "{{ ansible_check_mode }}"

- name: Gather facts on a file
  stat:
    path: /etc/hosts
  register: i

- name: Insert a line when condition is true
  when: i.stat.exists == true
  lineinfile:
    path: "{{ file_path }}/vars.html"
    line: "<p>File {{ i.stat.path }} exists. </p>"
  ignore_errors: "{{ ansible_check_mode }}"

- name: set a fact within a role
  set_fact:
    a_fact: the sky is blue

- name: insert a line using a_fact
  lineinfile:
    path: "{{ file_path }}/vars.html"
    line: "<p> {{ a_fact }}"
    insertafter: EOF
  ignore_errors: "{{ ansible_check_mode }}"
