---
- name: Install And configure Apache
  hosts: webservers
  become: yes
  become_user: root

  tasks:
  - name: Install Apache
    apt:
      name: apache2
      state: latest
      update_cache: yes
  - name: Enabling & Starting Service
    service:
      name: apache2
      enabled: yes
      state: started
  - name: remove existing index.html if exist
    file:
      path: /var/www/html/index.html
      state: absent
  - name: Create a  new empty index.html file if not exists
    file:
      path: /var/www/html/index.html
      state: touch
      owner: root
      group: root
      mode: 0755
  - name: Add content to index.html
    lineinfile:
      path: /var/www/html/index.html
      line: “Hello Happy Ansible World!”
